# Spring Config
spring:
  # Scheduling Config
  scheduling:
    enabled: false
  # DataSource Config
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.zaxxer.hikari.HikariDataSource
    platform: mysql
    username: wms
    password: FpLSHCiY66KaMxz7
    url: jdbc:p6spy:mysql://wms.aiairy.com:3316/wms?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&tinyInt1isBit=false&timezone=utc&useSSL=false&serverTimezone=Asia/Shanghai
# Socket Config
wss:
  server:
    enabled: false
    port: 3233
    host: 0.0.0.0
    upgrade-timeout: 10000
    timeout: 180000
    interval: 60000
# Logging Config
logging:
  config: classpath:logback-dev.xml
#=================================================================================
# 自定义参数相关配置
project:
  domain: https://aux.aiairy.com/
  # 文件资源配置
  oss:
    url: http://aux.aiairy.com/oss/
    yun-url: http://aux.aiairy.com/oss/
    path: /Users/nero/Projects/oss/