# APP
server:
  port: 8991
  servlet:
    context-path: /wms/api
spring:
  application:
    name: wms
  profiles:
    active: dev
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: ''
    jedis:
      pool:
        max-idle: 30
        max-wait: -1ms
        min-idle: 10
# Doc Config
knife4j:
  # 开启增强配置
  enable: true